#!/bin/sh

psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER" <<-EOSQL
	CREATE DATABASE $POSTGRES_DB;
	CREATE USER $POSTGRES_USER WITH PASSWORD $POSTGRES_PASSWORD;
	GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;
EOSQL
