version: '3'
services:

  static:
    build: ./static
    image: static
    hostname: static
    container_name: static
    restart: unless-stopped
    env_file:
      - ./env
      - ./static/env
    ports:
      - 7000:7000
    volumes:
      - ../volumes/app/:/var/www/
#     - ../logs:/var/log/lighttpd/error.log

  proxy:
    build: ./proxy
    image: proxy
    hostname: proxy
    container_name: proxy
    restart: unless-stopped
    env_file:
      - ./env
      - ./proxy/env
    depends_on:
      - accel
      - static
    ports:
      - 80:80
    volumes:
      - ../volumes/proxy:/var/lib/haproxy

  accel:
    build: ./accel
    image: accel
    hostname: accel
    container_name: accel
    restart: unless-stopped
    env_file:
      - ./env
      - ./accel/env
    depends_on:
      - app
    ports:
      - 9000:9000
    volumes:
      - ../volumes/accel:/var/lib/varnish

  app:
    build: ./app
    image: app
    hostname: app
    container_name: app
    restart: unless-stopped
    env_file:
      - ./env
      - ./app/env
    depends_on:
      - db
      - cache
      - broker
    ports:
      - 8000:8000
    volumes:
      - ../wypok:/app
      - ../volumes/app/static:/app/static
      - ../volumes/app/media:/app/media
      - ./app/etc/settings.ini:/app/wypok/settings/settings.ini

  db:
    build: ./db
    image: db
    hostname: db
    container_name: db
    restart: unless-stopped
    env_file:
      - ./env
      - ./db/env
    ports:
      - 5432:5432
    volumes:
      - ../volumes/db:/var/lib/postgresql/data

  cache:
    build: ./cache
    image: cache
    hostname: cache
    container_name: cache
    restart: unless-stopped
    env_file:
      - ./env
      - ./cache/env
    ports:
      - 6379:6379
    volumes:
      - ../volumes/cache:/data

  broker:
    build: ./broker
    image: broker
    hostname: broker
    container_name: broker
    restart: unless-stopped
    env_file:
      - ./env
      - ./broker/env
    ports:
      - 5672:5672
    volumes:
    - ../volumes/broker:/var/lib/rabbitmq

# email:
#   build: ./email
#   image: email
#   hostname: email
#   container_name: email
#   restart: unless-stopped
#   env_file:
#     - ./env
#     - ./email/env
#   ports:
#     - 5432:5432
#   volumes:
#     - ./volumes/email:/somewhere
#
